# See: http://about.travis-ci.org/docs/user/build-configuration/
# See: https://github.com/satooshi/php-coveralls

language: php
php:
  - 5.3

before_script:
  - cp phpunit-dist.xml phpunit.xml
  - curl -s http://getcomposer.org/installer | php
  - php composer.phar install --dev --no-interaction

script:
  - mkdir -p build/logs
  - ./vendor/bin/phpunit --configuration phpunit.xml --coverage-clover ./build/logs/clover.xml
  - ./vendor/bin/phpcs --standard=PSR2 ./src/

after_script:
  - php vendor/bin/coveralls -v

notifications:
  on_success: always
  on_failure: always
