# See: http://about.travis-ci.org/docs/user/build-configuration/

language: php
php:
  - 5.3

before_script:
  - cp phpunit-dist.xml phpunit.xml
  - composer install
script: phpunit --configuration phpunit.xml

notifications:
  on_success: always
  on_failure: always
